services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: compramais
      POSTGRES_PASSWORD: compramais
      POSTGRES_DB: compramais
    ports: ["5432:5432"]
    volumes: ["pgdata:/var/lib/postgresql/data"]
  db-test:
    image: postgres:16
    environment:
      POSTGRES_USER: compramais
      POSTGRES_PASSWORD: compramais
      POSTGRES_DB: compramais_test
    ports: ["5433:5432"]
    tmpfs: ["/var/lib/postgresql/data"]
volumes:
  pgdata:
